### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by tianshaokai** [yellowcath/PhotoMovie#10]
2018-12-12 17:40:19.058 573-7801/? E/MtkOmxVenc: [0xefb1e000] [ERROR] cannot init encode driver
    
    --------- beginning of crash
2018-12-12 17:40:19.059 7613-7796/? E/AndroidRuntime: FATAL EXCEPTION: GLMovieRecorder
    Process: com.hw.photomovie, PID: 7613
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2020)
        at com.hw.photomovie.record.GLMovieRecorder.releaseEncoder(GLMovieRecorder.java:275)
        at com.hw.photomovie.record.GLMovieRecorder.startRecordImpl(GLMovieRecorder.java:167)
        at com.hw.photomovie.record.GLMovieRecorder$1$1.run(GLMovieRecorder.java:87)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:232)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2018-12-12 17:40:19.059 7613-7798/? E/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] ERROR(0x80001005)

**Comment by tianshaokai** [comment]
018-12-12 17:40:19.201 1336-7806/? D/DropBoxManagerService: file :: /data/system/dropbox/2018@12@12@M6763B_11.A.30_0300_201809122357@com.hw.photomovie@data_app_crash@868055034486311_1544607619064_1544607619199.txt.gz
2018-12-12 17:40:19.205 1336-7806/? D/AES: onEndOfErrorDumpThread: data_app_crash Process: com.hw.photomovie
    Time: 1544607619064
    Flags: 0x38a8bf46
    Package: com.hw.photomovie v1 (1.0)
    PID: 7613
    Foreground: Yes
    Build: OPPO/A79/A79:7.1.1/N6F26Q/1536669917:user/release-keys
    
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2020)
        at com.hw.photomovie.record.GLMovieRecorder.releaseEncoder(GLMovieRecorder.java:275)
        at com.hw.photomovie.record.GLMovieRecorder.startRecordImpl(GLMovieRecorder.java:167)
        at com.hw.photomovie.record.GLMovieRecorder$1$1.run(GLMovieRecorder.java:87)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:232)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    
    CPU usage from 65091ms to 0ms ago (2018-12-12 17:39:14.009 to 2018-12-12 17:40:19.100):
      39% 370/surfaceflinger: 22% user + 16% kernel / faults: 1148 minor
      33% 3830/android.process.media: 33% user + 0% kernel / faults: 461 minor 3 major
      15% 1336/system_server: 11% user + 3.8% kernel / faults: 17528 minor 33 major
      12% 3304/com.android.systemui: 8.6% user + 3.4% kernel / faults: 5930 minor 8 major
      11% 6315/com.coloros.safesdkproxy: 11% user + 0.1% kernel / faults: 19594 minor 3 major
      9.8% 7012/adbd: 2.9% user + 6.8% kernel / faults: 9745 minor
      6.7% 310/logd: 1.9% user + 4.7% kernel / faults: 225 minor 1 major
      4.3% 10537/com.qiyi.video: 2.2% user + 2.1% kernel / faults: 422 minor 7 major
      3.4% 10582/com.qiyi.video:downloader: 2.4% user + 0.9% kernel / faults: 5811 minor 61 major
      3.1% 5531/com.android.packageinstaller: 2.3% user + 0.8% kernel / faults: 3173 minor 11 major
      2.5% 479/disp_queue_P0: 0% user + 2.5% kernel
      2.4% 3882/com.tencent.mm: 1.7% user + 0.7% kernel / faults: 248 minor 4 major
      2.3% 3443/com.tencent.mm:push: 1.8% user + 0.5% kernel / faults: 80 minor
      2% 96/kswapd0: 0% user + 2% kernel
      1.8% 7215/kworker/u17:3: 0% user + 1.8% kernel
      1.6% 885/kworker/u17:2: 0% user + 1.6% kernel
      1.6% 548/aal: 0.8% user + 0.7% kernel / faults: 14 minor
      1.5% 7068/logcat: 0.5% user + 0.9% kernel / faults: 35 minor
      1.4% 6523/kworker/u17:0: 0% user + 1.4% kernel
      1.4% 228/exe_cq: 0% user + 1.4% kernel
      0.8% 22423/kworker/u16:7: 0% user + 0.8% kernel
      1.3% 14583/kworker/u16:1: 0% user + 1.3% kernel
      1.2% 6899/logcat: 0.5% user + 0.6% kernel / faults: 50 minor
      1.1% 2246/com.nearme.statistics.rom: 0.8% user + 0.3% kernel / faults: 2277 minor
      1.1% 369/servicemanager: 0.4% user + 0.7% kernel / faults: 66 minor
      1.1% 1556/tx_thread: 0% user + 1.1% kernel
      1.1% 972/kworker/u16:2: 0% user + 1.1% kernel
      0.9% 7/rcu_preempt: 0% user + 0.9% kernel
      0.9% 1746/com.android.phone: 0.7% user + 0.1% kernel / faults: 1036 minor 5 major
      0.9% 2673/c
    
    --------- beginning of main
    12-12 17:40:18.276  7613  7640 I GLThread: waiting tid=2250 mHaveEglContext: true mHaveEglSurface: true mFinishedCreatingEglSurface: true mPaused: false mHasSurface: true mSurfaceIsBad: false mWaitingForSurface: false mWidth: 1080 mHeight: 1962 mRequestRender: false mRenderMode: 0
    12-12 17:40:18.288  7613  7640 W GLThread: onDrawFrame tid=2250
    12-12 17:40:18.294  7613  7640 I GLThread: waiting tid=2250 mHaveEglContext: true mHaveEglSurface: true mFinishedCreatingEglSurface: true mPaused: false mHasSurface: true mSurfaceIsBad: false mWaitingForSurface: false mWidth: 1080 mHeight: 1962 mRequestRender: false mRenderMode: 0
    12-12 17:40:18.305  7613  7640 W GLThread: onDrawFrame tid=2250
    12-12 17:40:18.310  7613  7640 I GLThread: waiting tid=2250 mHaveEglContext: true mHaveEglSurface: true mFinishedCreatingEglSurface: true mPaused: false mHasSurface: true mSurfaceIsBad: false mWaitingForSurface: false mWidth: 1080 mHeight: 1962 mRequestRender: false mRenderMode: 0
    12-12 17:40:18.322  7613  7640 W GLThread: onDrawFrame tid=2250
    12-12 17:40:18.326  7613  7640 I GLThread: waiting tid=2250 mHaveEglContext: true mHaveEglSurface: true mFinishedCreatingEglSurface: true mPaused: false mHa
2018-12-12 17:40:19.205 1336-7806/? W/AES: Exception Log handling...

**Comment by tianshaokai** [comment]
点击下一步报错的

**Comment by yellowcath** [comment]
implementation 'com.github.yellowcath:PhotoMovie:1.6.3'
编码器限制了1080X1920，超过最大尺寸会报错，已经做了限制

**Comment by tianshaokai** [comment]
嗯嗯，可否加一个监听回调呢，比如开始播放和结束播放的回调

**Comment by tianshaokai** [comment]
可否加作者你一个联系方式，学习一下android 高级技术

**Comment by yellowcath** [comment]
有回调的，PhotoMoviePlayer.setMovieListener

**Comment by yellowcath** [comment]
github简介里有联系方式的哦

**Comment by tianshaokai** [comment]
2018-12-17 15:50:01.200 476-490/system_process E/ActivityManager: ANR in com.hw.photomovie (com.hw.photomovie/me.iwf.photopicker.PhotoPickerActivity)
    PID: 1391
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 23.  Wait queue head age: 6005.1ms.)
    Load: 1.41 / 1.53 / 1.71
    CPU usage from 815606ms to 0ms ago (2018-12-17 15:36:23.275 to 2018-12-17 15:49:58.882):
      89% 865/com.vod: 85% user + 3.8% kernel / faults: 2293 minor
      21% 160/surfaceflinger: 7.9% user + 13% kernel / faults: 47329 minor
      17% 209/mediaserver: 7.1% user + 10% kernel / faults: 55795 minor
      1.9% 74/ksmd: 0% user + 1.9% kernel
      0.8% 55/cfinteractive: 0% user + 0.8% kernel
      0.8% 476/system_server: 0.3% user + 0.4% kernel / faults: 5995 minor
      0.6% 54/rk-fb: 0% user + 0.6% kernel
      0% 197/adbd: 0% user + 0% kernel / faults: 15941 minor
      0.4% 600/sdcard: 0.3% user + 0% kernel / faults: 6 minor
      0.2% 180/irq/41-20020000: 0% user + 0.2% kernel
      0.2% 53/fb-vsync: 0% user + 0.2% kernel
      0.1% 8/rcu_preempt: 0% user + 0.1% kernel
      0.1% 796/com.remote.service: 0.1% user + 0% kernel / faults: 959 minor
      0.1% 1237/kworker/u8:0: 0% user + 0.1% kernel
      0.1% 3/ksoftirqd/0: 0% user + 0.1% kernel
      0.1% 193/logd: 0% user + 0% kernel / faults: 5 minor
      0% 14/ksoftirqd/1: 0% user + 0% kernel
      0% 24/ksoftirqd/3: 0% user + 0% kernel
      0% 33/kworker/1:1: 0% user + 0% kernel
      0% 19/ksoftirqd/2: 0% user + 0% kernel
      0% 32/kworker/2:1: 0% user + 0% kernel
      0% 30/kworker/0:1: 0% user + 0% kernel
      0% 118/kworker/0:1H: 0% user + 0% kernel
      0% 787/android.process.media: 0% user + 0% kernel / faults: 1299 minor
      0% 1202/kworker/3:0: 0% user + 0% kernel
      0% 34/kconsole: 0% user + 0% kernel
      0% 200/audioserver: 0% user + 0% kernel / faults: 2 minor
      0% 123/mmcqd/0: 0% user + 0% kernel
      0% 568/com.android.systemui: 0% user + 0% kernel / faults: 186 minor
      0% 48/vmalloc: 0% user + 0% kernel
      0% 199/zygote: 0% user + 0% kernel / faults: 402 minor
      0% 125/ueventd: 0% user + 0% kernel / faults: 23 minor
      0% 144/jbd2/mmcblk0p14: 0% user + 0% kernel
      0% 159/servicemanager: 0% user + 0% kernel / faults: 49 minor
      0% 12/watchdog/1: 0% user + 0% kernel
      0% 15/kworker/1:0: 0% user + 0% kernel
      0% 204/installd: 0% user + 0% kernel / faults: 49 minor
      0% 807/com.android.inputmethod.latin: 0% user + 0% kernel / faults: 84 minor
      0% 844/com.rockchips.android.leanbacklauncher: 0% user + 0% kernel / faults: 88 minor
      0% 11/watchdog/0: 0% user + 0% kernel
      0% 17/watchdog/2: 0% user + 0% kernel
      0% 22/watchdog/3: 0% user + 0% kernel
      0% 28/kdevtmpfs: 0% user + 0% kernel
      0% 40/khubd: 0% user + 0% kernel
      0% 157/displayd: 0% user + 0% kernel / faults: 10 minor
      0% 158/lmkd: 0% user + 0% kernel
      0% 161/vold: 0% user + 0% kernel / faults: 13 minor
      0% 210/netd: 0% user + 0% kernel / faults: 44 minor
      0% 743/android.ext.services: 0% user + 0% kernel / faults: 61 minor
      0% 894/com.android.keychain: 0% user + 0% kernel / faults: 68 minor
      0% 1004/android.process.acore: 0% user + 0% kernel / faults: 112 minor
      0% 1036/com.android.providers.calendar: 0% user + 0% kernel / faults: 47 minor
     +0% 1244/kworker/u8:1: 0% user + 0% kernel
     +0% 1245/kworker/u8:2: 0% user + 0% kernel
     +0% 1255/kworker/3:1: 0% user + 0% kernel
     +0% 1256/kworker/2:2: 0% user + 0% kernel
     +0% 1267/logcat: 0% user + 0% kernel
     +0% 1270/kworker/0:0: 0% user + 0% kernel
     +0% 1279/sh: 0% user + 0% kernel
     +0% 1281/perfd: 0% user + 0% kernel
     +0% 1333/com.android.defcontainer: 0% user + 0% kernel
     +0% 1356/kworker/u9:2: 0% user + 0% kernel
     +0% 1360/com.svox.pico: 0% user + 0% kernel
     +0% 1391/com.hw.photomovie: 0% user + 0% kernel
    31% TOTAL: 26% user + 5.2% kernel + 0% iowait + 0% irq + 0% softirq
    CPU usage from 1759ms to 2285ms later (2018-12-17 15:50:00.640 to 2018-12-17 15:50:01.167):
      68% 600/sdcard: 53% user + 15% kernel
        66% 610/sdcard: 51% user + 15% kernel
      34% 1391/com.hw.photomovie: 28% user + 5.6% kernel / faults: 20 minor
        34% 1391/m.hw.photomovi
2018-12-17 15:50:01.349 476-1434/system_process I/mali_so: [File] : hardware/rockchip/driver/./src/base/arch/arch_011_udd/base_arch_main.c; [Line] : 565; [Func] : deal_with_version_affairs_rk_ext;
    arm_release_ver of this mali_so is 'r7p0-00rel1', rk_so_ver is '4@0' for 312x_android_7.1, built at '09:49:26', on 'Aug 18 2017'.
2018-12-17 15:50:01.349 476-1434/system_process I/mali_so: [File] : hardware/rockchip/driver/./src/base/arch/arch_011_udd/base_arch_main.c; [Line] : 578; [Func] : deal_with_version_affairs_rk_ext;
    mali_ver_property has been set to 'r7p0-00rel1-5-4@0', to return.
2018-12-17 15:50:01.351 476-1434/system_process I/OpenGLRenderer: Initialized EGL, version 1.4

获取图片时报错

**Comment by yellowcath** [comment]
这个是demo里用的开源控件
https://github.com/donglua/PhotoPicker
出问题了的话不影响库本身的使用，你可以在DemoActivity里直接调用
ArrayList<String> photos = new ArrayList<>();
...添加本地路径...
 mDemoPresenter.onPhotoPick(photos);

**Comment by tianshaokai** [comment]
好谢谢大佬啊
