### ISSUE TITLE
How To set ScaleType for window effect?

### ISSUE THREAD

**Issue by VineshChauhan24** [yellowcath/PhotoMovie#17]
i tried to change public ScaleType scaleType = ScaleType.FIT_XY; variable in Bitmap Info but still i can not set Scaletype for Window effect. i want to set Imgae ScaleType to Fit_Center

**Comment by yellowcath** [comment]
Maybe some segment didn't handle the scaletype?
See BitmapInfo. applyScaleType

**Comment by VineshChauhan24** [comment]
I have solved this issue by adding black color to landscape image and make it portrait and used that bitmap to create video

 private static Bitmap createSquaredBitmap(Bitmap srcBmp) {
        int dim = Math.max(srcBmp.getWidth(), srcBmp.getHeight());
        float aspect_ratio = (float)srcBmp.getWidth() / (float)srcBmp.getHeight() ;
        Bitmap dstBmp = Bitmap.createBitmap(dim, (int)(Math.ceil(srcBmp.getWidth()*aspect_ratio)), Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(dstBmp);
        canvas.drawColor(Color.BLACK);
        canvas.drawBitmap(srcBmp, (dim - srcBmp.getWidth()) / 2, (srcBmp.getWidth())/2 , null);

        return dstBmp;
    }


--------------------------------------------------------------------------------------

 if(bitmap.getHeight()<bitmap.getWidth())
        {
            Log.d("Orientation","landscape");
           return createSquaredBitmap(bitmap);
        }
        else
        {
            Log.d("Orientation","potrait");
            return bitmap;
        }

------------------------------------------------------------------------------------

create above method in SimplePhotodata

ThankYou
