### ISSUE TITLE
How to repeat the same song if more images use?

### ISSUE THREAD

**Issue by OriginInfotech** [yellowcath/PhotoMovie#18]

**Comment by yellowcath** [comment]
photoMoviePlayer. getMusicPlayer(). setLooping(true)

**Comment by daohieu91** [comment]
I did it but not working. :(

**Comment by daohieu91** [comment]
But the song is only looped in preview. How to record with the song looped?

**Comment by OriginInfotech** [comment]
yes it is working ,but not record..

**Comment by yellowcath** [comment]
This maybe a bug,see AudioRecordThread#117

**Comment by OriginInfotech** [comment]
it is working in .mp4a audio file format  but .mp3 audio not recorded..#77

                recordOtherAudio(extractor, format, audioTrackIndex);

**Comment by daohieu91** [comment]
I also guessed that there is some bugs in recordOtherAudio(extractor, format, audioTrackIndex) function. But still can not fix

**Comment by OriginInfotech** [comment]
In translation transition mp3 audio not recorded properly ,if someone get the solution please convey..

**Comment by yellowcath** [comment]
fixed
dependencies {
    implementation 'com.github.yellowcath:PhotoMovie:1.6.4'
}

**Comment by krushnarathod** [comment]
thank you for sharing this...

**Comment by qaiser9532** [comment]
in this library some pics are black whats the problem behind it...???
