### ISSUE TITLE
 How can I add stickers (or text) to videos?

### ISSUE THREAD

**Issue by LalaDev** [yellowcath/PhotoMovie#19]

**Comment by yellowcath** [comment]
https://github.com/yellowcath/PhotoMovie/blob/master/library/src/main/java/com/hw/photomovie/segment/layer/MovieTextLayer.java

**Comment by LalaDev** [comment]
thanks bro

**Comment by krushnarathod** [comment]
how to use this one to add stickers ?

**Comment by QaisBaig** [comment]
Ho to use 
https://github.com/yellowcath/PhotoMovie/blob/master/library/src/main/java/com/hw/photomovie/segment/layer/MovieTextLayer.java
this class ?
