### ISSUE TITLE
PhotoMovie duration is hardcoded

### ISSUE THREAD

**Issue by vikas-patel** [yellowcath/PhotoMovie#2]
Hey,

In current implementation total duration is photoMovie is fixed to the number of photos (Pasting the factory code below).
Can it be possible we assign the total duration of PhotoMovie and each photo display time is calculated based on total duration of PhotoMovie? In my need, I need to play the full song.
```
private static PhotoMovie generateHorizontalTransPhotoMovie(PhotoSource photoSource) {
        List<MovieSegment> segmentList = new ArrayList<MovieSegment>();
        for (int i = 0; i < photoSource.size(); i++) {
            segmentList.add(new FitCenterSegment(1000).setBackgroundColor(0xFF323232));
            segmentList.add(new MoveTransitionSegment(MoveTransitionSegment.DIRECTION_HORIZON, 800));
        }
        segmentList.remove(segmentList.size() - 1);
        PhotoMovie photoMovie = new PhotoMovie(photoSource, segmentList);
        return photoMovie;
    }
```

**Comment by yellowcath** [comment]
you can try this code:
 private static PhotoMovie generateHorizontalTransPhotoMovie(PhotoSource photoSource, int totalDurationMs) {
        int fitCenterSegmentDurationMs = 1000;
        int movieSegmentsTotalDutationMs = totalDurationMs - fitCenterSegmentDurationMs;
        int movieSegmentDutationMs = 800;

        float movieSegmentCount = movieSegmentsTotalDutationMs / (float) movieSegmentDutationMs;
        int lastMovieSegmentsDuration = (int) ((movieSegmentCount - ((int) movieSegmentCount) + 1) * movieSegmentDutationMs);
        List<MovieSegment> segmentList = new ArrayList<MovieSegment>();
        segmentList.add(new FitCenterSegment(fitCenterSegmentDurationMs).setBackgroundColor(0xFF323232));
        for (int i = 0; i < (int)movieSegmentCount - 1; i++) {
            segmentList.add(new MoveTransitionSegment(MoveTransitionSegment.DIRECTION_HORIZON, movieSegmentDutationMs));
        }
        segmentList.add(new MoveTransitionSegment(MoveTransitionSegment.DIRECTION_HORIZON, lastMovieSegmentsDuration));
        PhotoMovie photoMovie = new PhotoMovie(photoSource, segmentList);
        return photoMovie;
    }

**Comment by vikas-patel** [comment]
Hey,

I may be wrong, but it seems we should iterate through photoSource size. We are only adding first photo segment and multiple transition segments but not all photo segments (FitCenterSegment).

**Comment by yellowcath** [comment]
MovieSegment and PhotoData are not one-to-one，PhotoAllocator will allocate photos to MovieSegments,if MovieSegments is more than Photos,it will allocate repeatly.

**Comment by vikas-patel** [comment]
Ohh.. that's good :+1:

**Comment by vikas-patel** [comment]
Hey, I am getting following exception with the suggested code.

```
com.hw.photomovie.segment.TransitionSegment$TransitionSegmentException: TransitionSegment must be in the middle of two other Segments
        at com.hw.photomovie.segment.TransitionSegment.onPrepare(TransitionSegment.java:23)
        at com.hw.photomovie.segment.MoveTransitionSegment.onPrepare(MoveTransitionSegment.java:57)
        at com.hw.photomovie.segment.MovieSegment.prepare(MovieSegment.java:66)
        at com.hw.photomovie.PhotoMovie$SegmentPicker.pickCurrentSegment(PhotoMovie.java:129)
        at com.hw.photomovie.render.MovieRenderer.drawMovieFrame(MovieRenderer.java:34)
        at com.hw.photomovie.render.GLMovieRenderer.drawMovieFrame(GLMovieRenderer.java:71)
        at com.hw.photomovie.render.GLTextureMovieRender$1.onDrawFrame(GLTextureMovieRender.java:45)
        at com.hw.photomovie.render.GLTextureView$GLThread.guardedRun(GLTextureView.java:1465)
        at com.hw.photomovie.render.GLTextureView$GLThread.run(GLTextureView.java:1162)
```

**Comment by yellowcath** [comment]
sorry,I forot this.
new code:

>     private static PhotoMovie generateHorizontalTransPhotoMovie(PhotoSource photoSource, int totalDurationMs) {
        int fitCenterSegmentDurationMs = 1000;
        int movieSegmentDutationMs = 800;
        int segmentsTotalDutationMs = totalDurationMs;
        float segmentGroupCount = segmentsTotalDutationMs / (float) (movieSegmentDutationMs+fitCenterSegmentDurationMs);
        int extraDuration = (int) ((segmentGroupCount - ((int) segmentGroupCount) + 1) * movieSegmentDutationMs);
        List<MovieSegment> segmentList = new ArrayList<MovieSegment>();
        for (int i = 0; i < (int) segmentGroupCount; i++) {
            segmentList.add(new FitCenterSegment(fitCenterSegmentDurationMs).setBackgroundColor(0xFF323232));
            segmentList.add(new MoveTransitionSegment(MoveTransitionSegment.DIRECTION_HORIZON, movieSegmentDutationMs));
        }
        segmentList.add(new FitCenterSegment(extraDuration).setBackgroundColor(0xFF323232));
        PhotoMovie photoMovie = new PhotoMovie(photoSource, segmentList);
        return photoMovie;
    }

**Comment by vikas-patel** [comment]
thanks :+1:

**Comment by OriginInfotech** [comment]
How to add another view inside   GLTextureView to add text or sticker on video

**Comment by yellowcath** [comment]
TextureView is a normal view.
`
<FrameLayout
    ...>
      <GLTextureView 
            .../>
      <TextView 
            .../>
</FrameLayout>
`

**Comment by OriginInfotech** [comment]
by changing the GLTextureView  into viewgroup the above function cannot active,sticker are get on running   
video but sticker  cannot added in recorded video....how could i get that one.?

**Comment by Usama154** [comment]
java.lang.NoSuchMethodError: No virtual method centerCrop()Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.hw.photomovie-1/base.apk)

error when uploading photos

**Comment by Usama154** [comment]
error when i upload photo application close with above error ??

**Comment by Usama154** [comment]
当我上传照片应用程序关闭时出现上述错误？

**Comment by yellowcath** [comment]
glide是demo里的PhotoPicker引入的，不影响PhotoMovie库的使用，你可以直接在自己的项目引入PhotoMovie使用

**Comment by Usama154** [comment]
谢谢
