### ISSUE TITLE
添加音乐失败

### ISSUE THREAD

**Issue by jzqCode** [yellowcath/PhotoMovie#24]
添加音乐后保存视频失败

**Comment by yellowcath** [comment]
可能是不支持的音乐格式

**Comment by xkn874** [comment]
添加的是mp3。几张照片还可以生成，多几张就报错，如下。请问怎么解决？
java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)

**Comment by yellowcath** [comment]
能必现么？能的话可以把出错的图片和mp3传到网盘上，我试试看

**Comment by xkn874** [comment]
必现，和图片没有关系，估计是mp3的问题。
能加个QQ吗，方便把出错的图片和mp3发给你。QQ：2361066637

**Comment by leikko** [comment]
我也出现这个问题，请问下解决了吗？
