### ISSUE TITLE
Add Text/Logo (App name) in output video

### ISSUE THREAD

**Issue by vikas-patel** [yellowcath/PhotoMovie#3]
Hey,
In readme, I came across movieLayer which allows to add subtitles, but didn't find any example.
Can you please share any sample code? I just need to show the app name (text) at the corner of output video.

**Comment by yellowcath** [comment]
https://github.com/yellowcath/PhotoMovie/blob/master/library/src/main/java/com/hw/photomovie/segment/ScaleTransSegment.java
line 65 --->line 79

**Comment by vikas-patel** [comment]
Cool.. :+1:
