### ISSUE TITLE
Large output file size

### ISSUE THREAD

**Issue by vikas-patel** [yellowcath/PhotoMovie#4]
Hey,

I added the 9 photos (size 80-100kb) in photo movie demo app and no music. Generated output movie (horizontal trans) has a size of 7Mb (video duration 15 seconds).
Output movie picture quality is not very important for me, but the output file size should be small. Can there anything be done to reduce the output movie file.

**Comment by vikas-patel** [comment]
I set an smaller bit rate value to video processor, so it seems ok now.

**Comment by yellowcath** [comment]
https://github.com/yellowcath/PhotoMovie/blob/master/app/src/main/java/com/hw/photomovie/sample/DemoPresenter.java
line 202  
recorder.configOutput(glTextureView.getWidth(), glTextureView.getHeight(), bitrate, 30, 1, file.getAbsolutePath());

**Comment by vikas-patel** [comment]
Can't we add some compressor/encoder to reduce the output file size?

**Comment by yellowcath** [comment]
not support
